---
- name: Create ingress PriorityClass
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: scheduling.k8s.io/v1
      kind: PriorityClass
      metadata:
        name: ingress-high-priority
      value: 1000000
      globalDefault: false

- name: Install Traefik Ingress Controller chart
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    chart_ref: traefik
    chart_repo_url: https://traefik.github.io/charts
    chart_version: "38.0.0"
    create_namespace: true
    release_name: ingress-traefik
    release_namespace: ingress-traefik
    release_state: present
    release_values:
      fullnameOverride: ingress-traefik
      deployment:
        replicas: 3
      ingressClass:
        enabled: true
        isDefaultClass: true
        name: traefik
      priorityClassName: ingress-high-priority
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-traefik
      service:
        type: LoadBalancer
        annotations:
          kube-vip.io/loadbalancerIPs: "{{ ingress_traefik_load_balancer_ip }}"
        spec:
          externalTrafficPolicy: Local
      ports:
        web:
          nodePort: 31080
        websecure:
          nodePort: 31443
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
      autoscaling:
        enabled: true
        minReplicas: 3
      certificatesResolvers:
        letsencrypt:
          acme:
            email: "{{ traefik_cert_manager_acme_email | default('postmaster@sample.net') }}"
            storage: /data/acme.json
            caServer: "{{ traefik_cert_manager_acme_server | default('https://acme-v02.api.letsencrypt.org/directory') }}"
            httpChallenge:
              entryPoint: web
      persistence:
        enabled: true
        size: 300Mi
        storageClass: longhorn-rwx
        accessMode: ReadWriteMany
      logs:
        general:
          level: INFO
        access:
          enabled: true
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
    set_values:
      - value: "autoscaling.maxReplicas={{ ingress_autoscaling_max_replicas | default(3) | int }}"
        value_type: raw

- name: Install Traefik Internal Ingress Controller chart
  when: ingress_traefik_internal is defined
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    chart_ref: traefik
    chart_repo_url: https://traefik.github.io/charts
    chart_version: "38.0.0"
    create_namespace: true
    release_name: ingress-traefik-internal
    release_namespace: ingress-traefik-internal
    release_state: present
    release_values:
      fullnameOverride: ingress-traefik-internal
      deployment:
        replicas: 1
      ingressClass:
        enabled: true
        isDefaultClass: false
        name: traefik-internal
      service:
        type: LoadBalancer
        annotations:
          kube-vip.io/loadbalancerIPs: "{{ ingress_traefik_internal_load_balancer_ip }}"
        spec:
          externalTrafficPolicy: Local
      certificatesResolvers:
        letsencrypt:
          acme:
            email: "{{ traefik_cert_manager_acme_email | default('postmaster@sample.net') }}"
            storage: /data/acme.json
            caServer: "{{ traefik_cert_manager_acme_server | default('https://acme-v02.api.letsencrypt.org/directory') }}"
            httpChallenge:
              entryPoint: web
      persistence:
        enabled: true
        size: 300Mi
        storageClass: longhorn-rwx
        accessMode: ReadWriteMany
      autoscaling:
        enabled: false
        minReplicas: 1
    set_values:
      - value: "autoscaling.maxReplicas={{ ingress_autoscaling_max_replicas | default(3) | int }}"
        value_type: raw
